export const locations = [{ town: 'Aberdare', council: 'Mid Glamorgan'},
{ town: 'Aberdeen', council: 'Aberdeenshire'},
{ town: 'Aberdovey', council: 'Gwynedd'},
{ town: 'Abergavenny', council: 'Gwent'},
{ town: 'Abergele', council: 'Clwyd'},
{ town: 'Abertillery', council: 'Gwent'},
{ town: 'Aberystwyth', council: 'Dyfed'},
{ town: 'Abingdon', council: 'Oxfordshire'},
{ town: 'Accrington', council: 'Lancashire'},
{ town: 'Airdrie', council: 'Lanarkshire'},
{ town: 'Alcester', council: 'Warwickshire'},
{ town: 'Aldeburgh', council: 'Suffolk'},
{ town: 'Alderley Edge', council: 'Cheshire'},
{ town: 'Aldershot', council: 'Hampshire'},
{ town: 'Alfreton', council: 'Derbyshire'},
{ town: 'Alness', council: 'Ross-shire'},
{ town: 'Alnwick', council: 'Northumberland'},
{ town: 'Alresford', council: 'Hampshire'},
{ town: 'Alston', council: 'Cumbria'},
{ town: 'Alton', council: 'Hampshire'},
{ town: 'Altrincham', council: 'Cheshire'},
{ town: 'Ambleside', council: 'Cumbria'},
{ town: 'Amersham', council: 'Buckinghamshire'},
{ town: 'Amesbury', council: 'Wiltshire'},
{ town: 'Ammanford', council: 'Carmarthenshire'},
{ town: 'Andover', council: 'Hampshire'},
{ town: 'Anstruther', council: 'Fife'},
{ town: 'Antrim', council: 'Co Antrim'},
{ town: 'Appleby-in-Westmorland', council: 'Cumbria'},
{ town: 'Arbroath', council: 'Angus'},
{ town: 'Ardrossan', council: 'Ayrshire'},
{ town: 'Armagh', council: 'Co Armagh'},
{ town: 'Arthog', council: 'Gwynedd'},
{ town: 'Arundel', council: 'West Sussex'},
{ town: 'Ascot', council: 'Berkshire'},
{ town: 'Ashbourne', council: 'Derbyshire'},
{ town: 'Ashburton', council: 'Devon'},
{ town: 'Ashford', council: 'Kent'},
{ town: 'Ashford', council: 'Middlesex'},
{ town: 'Ashington', council: 'Northumberland'},
{ town: 'Ashtead', council: 'Surrey'},
{ town: 'Ashton-under-Lyne', council: 'Greater Manchester'},
{ town: 'Attleborough', council: 'Norfolk'},
{ town: 'Aviemore', council: 'Inverness-shire'},
{ town: 'Axminster', council: 'Devon'},
{ town: 'Aylesbury', council: 'Buckinghamshire'},
{ town: 'Ayr', council: 'Ayrshire'},
{ town: 'Bala', council: 'Gwynedd'},
{ town: 'Baldock', council: 'Hertfordshire'},
{ town: 'Ballachulish', council: 'Argyll'},
{ town: 'Ballycastle', council: 'Co Antrim'},
{ town: 'Ballyclare', council: 'Co Antrim'},
{ town: 'Ballymena', council: 'Co Antrim'},
{ town: 'Ballymoney', council: 'Co Antrim'},
{ town: 'Bamburgh', council: 'Northumberland'},
{ town: 'Bamstaple', council: 'Devon'},
{ town: 'Banbridge', council: 'Co Down'},
{ town: 'Banbury', council: 'Oxfordshire'},
{ town: 'Banchory', council: 'Kincardineshire'},
{ town: 'Banff', council: 'Aberdeenshire'},
{ town: 'Bangor', council: 'Co Down'},
{ town: 'Bangor', council: 'Gwynedd'},
{ town: 'Banstead', council: 'Surrey'},
{ town: 'Barking', council: 'Essex'},
{ town: 'Barmouth', council: 'Gwynedd'},
{ town: 'Barnard Castle', council: 'Co Durham'},
{ town: 'Barnet', council: 'Hertfordshire'},
{ town: 'Barnsley', council: 'South Yorkshire'},
{ town: 'Barnstaple', council: 'Devon'},
{ town: 'Barry', council: 'South Glamorgan'},
{ town: 'Barrow-in Furness', council: 'Cumbria'},
{ town: 'Barton-upon-Humber', council: 'South Humberside'},
{ town: 'Basildon', council: 'Essex'},
{ town: 'Basingstoke', council: 'Hampshire'},
{ town: 'Bath', council: 'Avon'},
{ town: 'Bathgate', council: 'West Lothian'},
{ town: 'Battle', council: 'East Sussex'},
{ town: 'Beaumaris', council: 'Gwynedd'},
{ town: 'Beccles', council: 'Suffolk'},
{ town: 'Beckenham', council: 'Kent'},
{ town: 'Bedale', council: 'North Yorkshire'},
{ town: 'Bedford', council: 'Bedfordshire'},
{ town: 'Belfast', council: 'Belfast'},
{ town: 'Belvedere', council: 'Kent'},
{ town: 'Benneet', council: 'Essex'},
{ town: 'Berkhamsted', council: 'Hertfordshire'},
{ town: 'Berwick-on-Tweed', council: 'Northumberland'},
{ town: 'Betws-y-Coed', council: 'Conwy'},
{ town: 'Beverley', council: 'North Humberside'},
{ town: 'Bewdley', council: 'Worcestershire'},
{ town: 'Bexhill-on-Sea', council: 'East Sussex'},
{ town: 'Bicester', council: 'Oxfordshire'},
{ town: 'Bideford', council: 'Devon'},
{ town: 'Biggar', council: 'Lanarkshire'},
{ town: 'Biggleswade', council: 'Bedfordshire'},
{ town: 'Billericay', council: 'Essex'},
{ town: 'Billingshurst', council: 'West Sussex'},
{ town: 'Bingley', council: 'West Yorkshire'},
{ town: 'Birkenhead', council: 'Merseyside'},
{ town: 'Birmingham', council: 'West Midlands'},
{ town: 'Bishop Auckland', council: 'Co Durham'},
{ town: 'Bishops Castle', council: 'Shropshire'},
{ town: 'Bishop\'s Stortford', council: 'Hertfordshire'},
{ town: 'Bishops Waltham', council: 'Hampshire'},
{ town: 'Blackburn', council: 'Lancashire'},
{ town: 'Blackpool', council: 'Lancashire'},
{ town: 'Blaenau Ffestiniog', council: 'Gwynedd'},
{ town: 'Blairgowrie', council: 'Perthshire'},
{ town: 'Blandford Forum', council: 'Dorset'},
{ town: 'Blaydon-on-Tyne', council: 'Tyne ＆ Wear'},
{ town: 'Bodmin', council: 'Cornwall'},
{ town: 'Bognor Regis', council: 'West Sussex'},
{ town: 'Boldon Colliery', council: 'Tyne ＆ Wear'},
{ town: 'Bolton', council: 'Lancashire'},
{ town: 'Bonnyrigg', council: 'Midlothian'},
{ town: 'Bootle', council: 'Merseyside'},
{ town: 'Bordon', council: 'Hampshire'},
{ town: 'Borehamwood', council: 'Hertfordshire'},
{ town: 'Boston', council: 'Lincolnshire'},
{ town: 'Botness', council: 'West Lothian'},
{ town: 'Bourne', council: 'Lincolnshire'},
{ town: 'Bournemouth', council: 'Dorset'},
{ town: 'Brackley', council: 'Northamptonshire'},
{ town: 'Bracknell', council: 'Berkshire'},
{ town: 'Bradford', council: 'West Yorkshire'},
{ town: 'Braintree', council: 'Essex'},
{ town: 'Brampton', council: 'Cumbria'},
{ town: 'Braunton', council: 'Devon'},
{ town: 'Brecon', council: 'Powys'},
{ town: 'Brentford', council: 'Middlesex'},
{ town: 'Brentwood', council: 'Essex'},
{ town: 'Bridgend', council: 'Mid Glamorgan'},
{ town: 'Bridgnorth', council: 'Shropshire'},
{ town: 'Bridgwater', council: 'Somerset'},
{ town: 'Bridlington', council: 'North Humberside'},
{ town: 'Bridport', council: 'Dorset'},
{ town: 'Brigg', council: 'Lincolnshire'},
{ town: 'Brighouse', council: 'West Yorkshire'},
{ town: 'Brighton', council: 'East Sussex'},
{ town: 'Bristol', council: 'Avon'},
{ town: 'Brixham', council: 'Devon'},
{ town: 'Broadford', council: 'Isle of Skye'},
{ town: 'Broadstairs', council: 'Kent'},
{ town: 'Broadway', council: 'Hereford ＆ Worcester'},
{ town: 'Brockenhurst', council: 'Hampshire'},
{ town: 'Brodick', council: 'Isle of Arran'},
{ town: 'Bromley', council: 'Kent'},
{ town: 'Bromsgrove', council: 'Hereford ＆ Worcester'},
{ town: 'Brooke', council: 'Norfolk'},
{ town: 'Broxburn', council: 'West Lothian'},
{ town: 'Buckfastleigh', council: 'Devon'},
{ town: 'Buckhurst Hill', council: 'Essex'},
{ town: 'Buckie', council: 'Banffshire'},
{ town: 'Buckingham', council: 'Buckinghamshire'},
{ town: 'Bude', council: 'Cornwall'},
{ town: 'Budleigh Salterton', council: 'Devon'},
{ town: 'Builth Wells', council: 'Powys'},
{ town: 'Bunessan', council: 'Isle of Mull'},
{ town: 'Bungay', council: 'Suffolk'},
{ town: 'Burgess Hill', council: 'West Sussex'},
{ town: 'Burnham-on-Sea', council: 'Somerset'},
{ town: 'Burnley', council: 'Lancashire'},
{ town: 'Burton-on-Trent', council: 'Staffordshire'},
{ town: 'Bury', council: 'Lancashire'},
{ town: 'Bury St Edmunds', council: 'Suffolk'},
{ town: 'Bushmills', council: 'Co Antrim'},
{ town: 'Buxton', council: 'Derbyshire'},
{ town: 'Caernarvon', council: 'Gwynedd'},
{ town: 'Caerphilly', council: 'Mid Glamorgan'},
{ town: 'Calne', council: 'Wiltshire'},
{ town: 'Camberley', council: 'Surrey'},
{ town: 'Cambridge', council: 'Cambridgeshire'},
{ town: 'Camelford', council: 'Cornwall'},
{ town: 'Campbeltown', council: 'Argyll'},
{ town: 'Cannock', council: 'Staffordshire'},
{ town: 'Canterbury', council: 'Kent'},
{ town: 'Cardiff', council: 'South Glamorgan'},
{ town: 'Cardigan', council: 'Dyfed'},
{ town: 'Carlisle', council: 'Cumbria'},
{ town: 'Carloway', council: 'Isle of Lewis'},
{ town: 'Carluke', council: 'Lanarkshire'},
{ town: 'Carmarthen', council: 'Dyfed'},
{ town: 'Carnforth', council: 'Lancashire'},
{ town: 'Carrickfergus', council: 'Co Antrim'},
{ town: 'Carshalton', council: 'Surrey'},
{ town: 'Castle Douglas', council: 'Kirkcudbrightshire'},
{ town: 'Castlederg', council: 'Co Tyrone'},
{ town: 'Castletown', council: 'Isle of Man'},
{ town: 'Castlewellan', council: 'Co Down'},
{ town: 'Caterham', council: 'Surrey'},
{ town: 'Cemmaes Bay', council: 'Gwynedd'},
{ town: 'Cemmaes Road', council: 'Gwynedd'},
{ town: 'Cerne Abbas', council: 'Dorset'},
{ town: 'Chard', council: 'Somerset'},
{ town: 'Chatham', council: 'Kent'},
{ town: 'Chatteris', council: 'Cambridgeshire'},
{ town: 'Cheadle', council: 'Cheshire'},
{ town: 'Cheam', council: 'Surrey'},
{ town: 'Cheddar', council: 'Somerset'},
{ town: 'Chelmsford', council: 'Essex'},
{ town: 'Cheltenham', council: 'Gloucestershire'},
{ town: 'Chepstow', council: 'Gwent'},
{ town: 'Chertsey', council: 'Surrey'},
{ town: 'Chesham', council: 'Buckinghamshire'},
{ town: 'Chester', council: 'Cheshire'},
{ town: 'Chester-le-Street', council: 'Co Durham'},
{ town: 'Chesterfield', council: 'Derbyshire'},
{ town: 'Chichester', council: 'West Sussex'},
{ town: 'Chippenham', council: 'Wiltshire'},
{ town: 'Chipping Norton', council: 'Oxfordshire'},
{ town: 'Chipping Sodbury', council: 'Gloucestershire'},
{ town: 'Chorley', council: 'Lancashire'},
{ town: 'Christchurch', council: 'Dorset'},
{ town: 'Church Stretton', council: 'Shropshire'},
{ town: 'Cinderford', council: 'Gloucestershne'},
{ town: 'Cirencester', council: 'Gloucestershire'},
{ town: 'Clacton-on-Sea', council: 'Essex'},
{ town: 'Cleethorpes', council: 'South Humberside'},
{ town: 'Clevedon', council: 'Avon'},
{ town: 'Clitheroe', council: 'Lancashire'},
{ town: 'Clogher', council: 'Co Tyrone'},
{ town: 'Clopton', council: 'Northamptonshire'},
{ town: 'Coalville', council: 'Leicestershire'},
{ town: 'Coatbridge', council: 'Lanarkshire'},
{ town: 'Cobham', council: 'Surrey'},
{ town: 'Cockermouth', council: 'Cumbria'},
{ town: 'Colchester', council: 'Essex'},
{ town: 'Coleshill', council: 'Warwickshire'},
{ town: 'Coleraine', council: 'Co Londonderry'},
{ town: 'Colwyn Bay', council: 'Clwyd'},
{ town: 'Congleton', council: 'Cheshire'},
{ town: 'Coniston', council: 'Cumbria'},
{ town: 'Consett', council: 'Co Durham'},
{ town: 'Conwy', council: 'Gwynedd'},
{ town: 'Cookstown', council: 'Co Tyrone'},
{ town: 'Coppull', council: 'Lancashire'},
{ town: 'Corbridge', council: 'Northumberland'},
{ town: 'Corby', council: 'Northamptonshire'},
{ town: 'Corwen', council: 'Clwyd'},
{ town: 'Coulsdon', council: 'Surrey'},
{ town: 'Coventry', council: 'West Midlands'},
{ town: 'Craigavon', council: 'Co Armagh'},
{ town: 'Cramlington', council: 'Northumberland'},
{ town: 'Cranbrook', council: 'Kent'},
{ town: 'Cranleigh', council: 'Surrey'},
{ town: 'Craven Arms', council: 'Shropshire'},
{ town: 'Crawley', council: 'West Sussex'},
{ town: 'Crediton', council: 'Devon'},
{ town: 'Crewe', council: 'Cheshire'},
{ town: 'Crieff', council: 'Perthshire'},
{ town: 'Cromer', council: 'Norfolk'},
{ town: 'Crowborough', council: 'East Sussex'},
{ town: 'Croy', council: 'Inverness-shire'},
{ town: 'Croydon', council: 'Surrey'},
{ town: 'Crumlin', council: 'Co Antrim'},
{ town: 'Cullompton', council: 'Devon'},
{ town: 'Cumnock', council: 'East Ayrshire'},
{ town: 'Cupar', council: 'Fife'},
{ town: 'Cwmbran', council: 'Gwent'},
{ town: 'Dagenham', council: 'Essex'},
{ town: 'Dalbeattie', council: 'Kirkcudbrightshire'},
{ town: 'Dalmally', council: 'Argyll'},
{ town: 'Dalry', council: 'Ayrshire'},
{ town: 'Darlington', council: 'Co Durham'},
{ town: 'Dartford', council: 'Kent'},
{ town: 'Darvel', council: 'Ayrshire'},
{ town: 'Daventry', council: 'Northamptonshire'},
{ town: 'Deal', council: 'Kent'},
{ town: 'Deeside', council: 'Clwyd'},
{ town: 'Derby', council: 'Derbyshire'},
{ town: 'Dereham', council: 'Norfolk'},
{ town: 'Devizes', council: 'Wiltshire'},
{ town: 'Dewsbury', council: 'West Yorkshire'},
{ town: 'Didcot', council: 'Oxfordshire'},
{ town: 'Dinas Powis', council: 'South Glamorgan'},
{ town: 'Dingwall', council: 'Ross-shire'},
{ town: 'Diss', council: 'Norfolk'},
{ town: 'Dolgellau', council: 'Gwynedd'},
{ town: 'Doncaster', council: 'South Yorkshire'},
{ town: 'Dorchester', council: 'Dorset'},
{ town: 'Dorking', council: 'Surrey'},
{ town: 'Dornoch', council: 'Sutherland'},
{ town: 'Douglas', council: 'Isle of Man'},
{ town: 'Dover', council: 'Kent'},
{ town: 'Downham Market', council: 'Norfolk'},
{ town: 'Downpatrick', council: 'Co Down'},
{ town: 'Driffield', council: 'North Humberside'},
{ town: 'Droitwich', council: 'Hereford ＆ Worcester'},
{ town: 'Dromore', council: 'Co Down'},
{ town: 'Dudley', council: 'West Midlands'},
{ town: 'Dulverton', council: 'Somerset'},
{ town: 'Dumbarton', council: 'Dunbartonshire'},
{ town: 'Dumfries', council: 'Dumfriesshire'},
{ town: 'Dunbar', council: 'East Lothian'},
{ town: 'Dunblane', council: 'Perthshire'},
{ town: 'Dundee', council: 'Angus'},
{ town: 'Dunfermline', council: 'Fife'},
{ town: 'Dungannon', council: 'Co Tyrone'},
{ town: 'Dunkeld', council: 'Perthshire'},
{ town: 'Dunmow', council: 'Essex'},
{ town: 'Dunmurry', council: 'Belfast'},
{ town: 'Dunoon', council: 'Argyll'},
{ town: 'Duns', council: 'Berwickshire'},
{ town: 'Dunstable', council: 'Bedfordshire'},
{ town: 'Durham', council: 'Co Durham'},
{ town: 'Dursley', council: 'Gloucestershire'},
{ town: 'Easingwold', council: 'North Yorkshire'},
{ town: 'East Grinstead', council: 'West Sussex'},
{ town: 'East Kilbride', council: 'South Lanarkshire'},
{ town: 'East Molesey', council: 'Surrey'},
{ town: 'Eastbourne', council: 'East Sussex'},
{ town: 'Eastleigh', council: 'Hampshire'},
{ town: 'Ebbsfleet', council: 'Kent'},
{ town: 'Ebbw Vale', council: 'Gwent'},
{ town: 'Edenbridge', council: 'Kent'},
{ town: 'Edgware', council: 'Middlesex'},
{ town: 'Edinburgh', council: 'Edinburgh'},
{ town: 'Egham', council: 'Surrey'},
{ town: 'Elgin', council: 'Morayshire'},
{ town: 'Ellesmere Port', council: 'Cheshire'},
{ town: 'Ellon', council: 'Aberdeenshire'},
{ town: 'Ely', council: 'Cambridgeshire'},
{ town: 'Emsworth', council: 'Hampshire'},
{ town: 'Enfeld', council: 'Middlesex'},
{ town: 'Enniskillen', council: 'Co Fermanagh'},
{ town: 'Epping', council: 'Essex'},
{ town: 'Epsom', council: 'Surrey'},
{ town: 'Erith', council: 'Kent'},
{ town: 'Esher', council: 'Surrey'},
{ town: 'Evesham', council: 'Worcestershire'},
{ town: 'Exeter', council: 'Devon'},
{ town: 'Exmouth', council: 'Devon'},
{ town: 'Fakenham', council: 'Norfolk'},
{ town: 'Falkirk', council: 'Stirlingshire'},
{ town: 'Falmouth', council: 'Cornwall'},
{ town: 'Fareham', council: 'Hampshire'},
{ town: 'Faringdon', council: 'Oxfordshire'},
{ town: 'Farnborough', council: 'Hampshire'},
{ town: 'Farnham', council: 'Surrey'},
{ town: 'Felixstowe', council: 'Suffolk'},
{ town: 'Fishguard', council: 'Dyfed'},
{ town: 'Fivemiletown', council: 'Co Tyrone'},
{ town: 'Fleet', council: 'Hampshire'},
{ town: 'Fleetwood', council: 'Lancashire'},
{ town: 'Flint', council: 'Clwyd'},
{ town: 'Folkestone', council: 'Kent'},
{ town: 'Forfar', council: 'Angus'},
{ town: 'Fort William', council: 'Inverness-shire'},
{ town: 'Fortrose', council: 'Ross-shire'},
{ town: 'Fowey', council: 'Cornwall'},
{ town: 'Fraserburgh', council: 'Aberdeenshire'},
{ town: 'Freshwater', council: 'Isle of Wight'},
{ town: 'Frinton-on-Sea', council: 'Essex'},
{ town: 'Frome', council: 'Somerset'},
{ town: 'Gainsborough', council: 'Lincolnshire'},
{ town: 'Gairloch', council: 'Ross-shire'},
{ town: 'Galasheils', council: 'Selkirkshire'},
{ town: 'Garstang', council: 'Lancashire'},
{ town: 'Gateshead', council: 'Tyne ＆ Wear'},
{ town: 'Gerrards Cross', council: 'Buckinghamshire'},
{ town: 'Gillingham', council: 'Dorset'},
{ town: 'Gillingham', council: 'Kent'},
{ town: 'Girvan', council: 'South Ayrshire'},
{ town: 'Glamorgan', council: 'Rotherham'},
{ town: 'Glasgow', council: 'Glasgow'},
{ town: 'Glastonbury', council: 'Somerset'},
{ town: 'Glenrothes', council: 'Fife'},
{ town: 'Glossop', council: 'Derbyshire'},
{ town: 'Gloucester', council: 'Gloucestershire'},
{ town: 'Godalming', council: 'Surrey'},
{ town: 'Godstone', council: 'Surrey'},
{ town: 'Goole', council: 'East Riding of Yorkshire'},
{ town: 'Gosforth', council: 'Cumbria'},
{ town: 'Gosport', council: 'Hampshire'},
{ town: 'Grange-over-Sands', council: 'Cumbria'},
{ town: 'Grangemouth', council: 'Midlothian'},
{ town: 'Grantham', council: 'Lincolnshire'},
{ town: 'Gravesend', council: 'Kent'},
{ town: 'Grays Thurrock', council: 'Essex'},
{ town: 'Great Dunmow', council: 'Essex'},
{ town: 'Great Missenden', council: 'Buckinghamshire'},
{ town: 'Great Yarmouth', council: 'Norfolk'},
{ town: 'Greenford', council: 'Middlesex'},
{ town: 'Greenock', council: 'Renfrewshire'},
{ town: 'Gretna', council: 'Dumfriesshire'},
{ town: 'Grimsby', council: 'South Humberside'},
{ town: 'Guernsey', council: 'Channel Islands'},
{ town: 'Guildford', council: 'Surrey'},
{ town: 'Guisborough', council: 'North Yorkshire'},
{ town: 'Guiseley', council: 'West Yorkshire'},
{ town: 'Gullane', council: 'East Lothian'},
{ town: 'Hamilton', council: 'Lanark shire'},
{ town: 'Haddington', council: 'East Lothian'},
{ town: 'Hailsham', council: 'East Sussex'},
{ town: 'Halesowen', council: 'West Midlands'},
{ town: 'Halifax', council: 'West Yorkshire'},
{ town: 'Halstead', council: 'Essex'},
{ town: 'Haltwhistle', council: 'Northumberland'},
{ town: 'Hampton', council: 'Middlesex'},
{ town: 'Harlow', council: 'Essex'},
{ town: 'Harpenden', council: 'Hertfordshire'},
{ town: 'Harrogate', council: 'North Yorkshire'},
{ town: 'Harrow', council: 'Middlesex'},
{ town: 'Hartlepool', council: 'Cleveland'},
{ town: 'Harwich', council: 'Essex'},
{ town: 'Haslemere', council: 'Surrey'},
{ town: 'Hassocks', council: 'West Sussex'},
{ town: 'Hastings', council: 'East Sussex'},
{ town: 'Hatfield', council: 'Hertfordshire'},
{ town: 'Hathersage', council: 'Derbyshire'},
{ town: 'Havant', council: 'Hampshire'},
{ town: 'Haverfordwest', council: 'Pembrokeshire'},
{ town: 'Haverhill', council: 'Suffolk'},
{ town: 'Hawick', council: 'Roxburghshire'},
{ town: 'Hawkshead', council: 'Cumbria'},
{ town: 'Hay-on-Wye', council: 'Powys'},
{ town: 'Hayes', council: 'Middlesex'},
{ town: 'Hayling Island', council: 'Hampshire'},
{ town: 'Haywards Heath', council: 'West Sussex'},
{ town: 'Heanor', council: 'Derbyshire'},
{ town: 'Heathfield', council: 'East Sussex'},
{ town: 'Hebden Bridge', council: 'West Yorkshire'},
{ town: 'Helensburgh', council: 'Dunbartonshire'},
{ town: 'Helmsley', council: 'North Yorkshire'},
{ town: 'Helston', council: 'Cornwall'},
{ town: 'Hemel Hempstead', council: 'Hertfordshire'},
{ town: 'Henfield', council: 'West Sussex'},
{ town: 'Henley-on-Thames', council: 'Oxfordshire'},
{ town: 'Hereford', council: 'Hereford ＆ Worcester'},
{ town: 'Herne Bay', council: 'Kent'},
{ town: 'Hertford', council: 'Hertfordshire'},
{ town: 'Hessle', council: 'North Humberside'},
{ town: 'Hexham', council: 'Northumberland'},
{ town: 'Heywood', council: 'Lancashire'},
{ town: 'High Wycombe', council: 'Buckinghamshire'},
{ town: 'Highbridge', council: 'Somerset'},
{ town: 'Hillsborough', council: 'Co Down'},
{ town: 'Hinckley', council: 'Leicestershire'},
{ town: 'Hindhead', council: 'Surrey'},
{ town: 'Hitchin', council: 'Hertfordshire'},
{ town: 'Hockley', council: 'Essex'},
{ town: 'Hoddesdon', council: 'Hertfordshire'},
{ town: 'Holbeach', council: 'Lincolnshire'},
{ town: 'Holmes Chapel', council: 'Cheshire'},
{ town: 'Holsworthy', council: 'Devon'},
{ town: 'Holt', council: 'Norfolk'},
{ town: 'Holyhead', council: 'Gwynedd'},
{ town: 'Holywood', council: 'Co Down'},
{ town: 'Honington', council: 'Lincolnshire'},
{ town: 'Honiton', council: 'Devon'},
{ town: 'Hook', council: 'Hampshire'},
{ town: 'Horley', council: 'Surrey'},
{ town: 'Hornby', council: 'Lancashire'},
{ town: 'Hornchurch', council: 'Essex'},
{ town: 'Hornsea', council: 'East Riding of Yorkshire'},
{ town: 'Horsham', council: 'West Sussex'},
{ town: 'Houghton le Spring', council: 'Tyne ＆ Wear'},
{ town: 'Hounslow', council: 'Middlesex'},
{ town: 'Hove', council: 'East Sussex'},
{ town: 'Huddersfield', council: 'West Yorkshire'},
{ town: 'Hull', council: 'North Humberside'},
{ town: 'Hungerford', council: 'Berkshire'},
{ town: 'Hunstanton', council: 'Norfolk'},
{ town: 'Huntingdon', council: 'Cambridgeshire'},
{ town: 'Huntly', council: 'Aberdeenshire'},
{ town: 'Hyde', council: 'Cheshire'},
{ town: 'Hythe', council: 'Kent'},
{ town: 'Ilford', council: 'Essex'},
{ town: 'Ilfracombe', council: 'Devon'},
{ town: 'Ilkeston', council: 'Derbyshire'},
{ town: 'Ilkley', council: 'West Yorkshire'},
{ town: 'Immingham', council: 'South Humberside'},
{ town: 'Ingatestone', council: 'Essex'},
{ town: 'Insch', council: 'Aberdeenshire'},
{ town: 'Inveraray', council: 'Argyll'},
{ town: 'Inverness', council: 'Inverness-shire'},
{ town: 'Inverurie', council: 'Aberdeenshire'},
{ town: 'Iona', council: 'Isle of Iona'},
{ town: 'Ipstones', council: 'Staffordshire'},
{ town: 'Ipswich', council: 'Suffolk'},
{ town: 'Ironbridge', council: 'Shropshire'},
{ town: 'Isle of Wight', council: 'Isle of Wight'},
{ town: 'Isleworth', council: 'Middlesex'},
{ town: 'Jersey', council: 'Channel Islands'},
{ town: 'Johnstone', council: 'Renfrewshire'},
{ town: 'Keighley', council: 'West Yorkshire'},
{ town: 'Kelso', council: 'Roxburghshire'},
{ town: 'Kendal', council: 'Cumbria'},
{ town: 'Kenilworth', council: 'Warwickshire'},
{ town: 'Keswick', council: 'Cumbria'},
{ town: 'Kettering', council: 'Northamptonshire'},
{ town: 'Kidderminster', council: 'Hereford \＆ Worcester'},
{ town: 'Kilbirnie', council: 'Ayrshire'},
{ town: 'Killin', council: 'Perthshire'},
{ town: 'Killingholme', council: 'Lincolnshire'},
{ town: 'Kilmacolm', council: 'Renfrewshire'},
{ town: 'Kilmarnock', council: 'Ayrshire'},
{ town: 'King\'s Lynn', council: 'Norfolk'},
{ town: 'Kings Langley', council: 'Hertfordshire'},
{ town: 'Kingsbridge', council: 'Devon'},
{ town: 'Kingston upon Thames', council: 'Surrey'},
{ town: 'Kingswinford', council: 'West Midlands'},
{ town: 'Kington', council: 'Herefordshire'},
{ town: 'Kingussie', council: 'Inverness-shire'},
{ town: 'Kirkby Stephen', council: 'Cumbria'},
{ town: 'Kirkcaldy', council: 'Fife'},
{ town: 'Kirkwhelpington', council: 'Northumberland'},
{ town: 'Kirriemuir', council: 'Angus'},
{ town: 'Knighton', council: 'Powys'},
{ town: 'Knutsford', council: 'Cheshire'},
{ town: 'Kyle', council: 'Ross-shire'},
{ town: 'Kyleakin', council: 'Isle of Skye'},
{ town: 'Laindon', council: 'Essex'},
{ town: 'Lairg', council: 'Sutherland'},
{ town: 'Lampeter', council: 'Ceredigion'},
{ town: 'Lanark', council: 'Lanarkshire'},
{ town: 'Lancaster', council: 'Lancashire'},
{ town: 'Lancing', council: 'West Sussex'},
{ town: 'Lapworth', council: 'Warwickshire'},
{ town: 'Larbert', council: 'Stirlingshire'},
{ town: 'Latheron', council: 'Caithness'},
{ town: 'Launceston', council: 'Cornwall'},
{ town: 'Leamington Spa', council: 'Warwickshire'},
{ town: 'Leatherhead', council: 'Surrey'},
{ town: 'Ledbury', council: 'Hereford ＆ Worcester'},
{ town: 'Leeds', council: 'West Yorkshire'},
{ town: 'Leicester', council: 'Leicestershire'},
{ town: 'Leigh', council: 'Lancashire'},
{ town: 'Leigh-on-Sea', council: 'Essex'},
{ town: 'Leighton Buzzard', council: 'Bedfordshire'},
{ town: 'Leiston', council: 'Suffolk'},
{ town: 'Leominster', council: 'Hereford ＆ Worcester'},
{ town: 'Lerwick', council: 'Isle of Shetland'},
{ town: 'Letchworth', council: 'Hertfordshire'},
{ town: 'Lewes', council: 'East Sussex'},
{ town: 'Leyburn', council: 'North Yorkshire'},
{ town: 'Leyland', council: 'Lancashire'},
{ town: 'Lichfield', council: 'Staffordshire'},
{ town: 'Lightwater', council: 'Surrey'},
{ town: 'Limavady', council: 'Co Londonderry'},
{ town: 'Lincoln', council: 'Lincolnshire'},
{ town: 'Lingfield', council: 'Surrey'},
{ town: 'Liphook', council: 'Hampshire'},
{ town: 'Lisburn', council: 'Co Antrim'},
{ town: 'Liskeard', council: 'Cornwall'},
{ town: 'Liss', council: 'Hampshire'},
{ town: 'Littleborough', council: 'Lancashire'},
{ town: 'Littlehampton', council: 'West Sussex'},
{ town: 'Liverpool', council: 'Merseyside'},
{ town: 'Livingston', council: 'West Lothian'},
{ town: 'Llanarth', council: 'Ceredigion'},
{ town: 'Llanbedr', council: 'Gwynedd'},
{ town: 'Llandeilo', council: 'Carmarthenshire'},
{ town: 'Llandovery', council: 'Carmarthenshire'},
{ town: 'Llandrindod Wells', council: 'Powys'},
{ town: 'Llandudno', council: 'Gwynedd'},
{ town: 'Llandysul', council: 'Dyfed'},
{ town: 'Llanelli', council: 'Dyfed'},
{ town: 'Llangollen', council: 'Clwyd'},
{ town: 'Llanidloes', council: 'Powys'},
{ town: 'Llanon', council: 'Ceredigion'},
{ town: 'Llanrwst', council: 'Gwynedd'},
{ town: 'Llantwit', council: 'South Glamorgan'},
{ town: 'Llanwrda', council: 'Dyfed'},
{ town: 'Llanwrtyd Wells', council: 'Powys'},
{ town: 'Loanhead', council: 'Midlothian'},
{ town: 'Lochboisdale', council: 'Isle of Uist'},
{ town: 'Lochcarron', council: 'Ross-shire'},
{ town: 'Lochgilphead', council: 'Argyll'},
{ town: 'Lochwinnoch', council: 'Renfrewshire'},
{ town: 'Lockerbie', council: 'Dumfriesshire'},
{ town: 'London', council: 'London'},
{ town: 'Londonderry', council: 'Co Londonderry'},
{ town: 'Loughborough', council: 'Leicestershire'},
{ town: 'Loughton', council: 'Essex'},
{ town: 'Louth', council: 'Lincolnshire'},
{ town: 'Lowestoft', council: 'Suffolk'},
{ town: 'Ludlow', council: 'Shropshire'},
{ town: 'Lurgan', council: 'Co Antrim'},
{ town: 'Luton', council: 'Bedfordshire'},
{ town: 'Lutterworth', council: 'Leicestershire'},
{ town: 'Lydney', council: 'Gloucestershire'},
{ town: 'Lymington', council: 'Hampshire'},
{ town: 'Lyndhurst', council: 'Hampshire'},
{ town: 'Lynton', council: 'Devon'},
{ town: 'Lytham StAnnes', council: 'Lancashire'},
{ town: 'Macclesfield', council: 'Cheshire'},
{ town: 'Machynlleth', council: 'Powys'},
{ town: 'Madingley', council: 'Cambridgeshire'},
{ town: 'Maesteg', council: 'Mid Glamorgan'},
{ town: 'Magharafelt', council: 'Co Londonderry'},
{ town: 'Maidenhead', council: 'Berkshire'},
{ town: 'Maidstone', council: 'Kent'},
{ town: 'Maldon', council: 'Essex'},
{ town: 'Malmesbury', council: 'Wiltshire'},
{ town: 'Malpas', council: 'Cheshire'},
{ town: 'Malton', council: 'North Yorkshire'},
{ town: 'Malvern', council: 'Hereford ＆ Worcester'},
{ town: 'Manchester', council: 'Greater Manchester'},
{ town: 'Mansfield', council: 'Nottinghamshire'},
{ town: 'March', council: 'Cambridgeshire'},
{ town: 'Margate', council: 'Kent'},
{ town: 'Market Drayton', council: 'Shropshire'},
{ town: 'Market Harborough', council: 'Leicestershire'},
{ town: 'Market Rasen', council: 'Lincolnshire'},
{ town: 'Market Weighton', council: 'East Riding of Yorkshire'},
{ town: 'Marlborough', council: 'Wiltshire'},
{ town: 'Marlow', council: 'Buckinghamshire'},
{ town: 'Martin', council: 'Lincolnshire'},
{ town: 'Maryport', council: 'Cumbria'},
{ town: 'Matlock', council: 'Derbyshire'},
{ town: 'Maud', council: 'Aberdeenshire'},
{ town: 'Medway', council: 'Kent'},
{ town: 'Meifod', council: 'Powys'},
{ town: 'Melksham', council: 'Wiltshire'},
{ town: 'Melton Mowbray', council: 'Leicestershire'},
{ town: 'Mere', council: 'Wiltshire'},
{ town: 'Meriden', council: 'West Midlands'},
{ town: 'Merthyr Tydfil', council: 'Mid Glamorgan'},
{ town: 'Mexborough', council: 'South Yorkshire'},
{ town: 'Middlesbrough', council: 'Cleveland'},
{ town: 'Middlewich', council: 'Cheshire'},
{ town: 'Midhurst', council: 'West Sussex'},
{ town: 'Mildenhall', council: 'Suffolk'},
{ town: 'Milford Haven', council: 'Pembrokeshire'},
{ town: 'Milton Keynes', council: 'Buckinghamshire'},
{ town: 'Minehead', council: 'Somerset'},
{ town: 'Mirfield', council: 'West Yorkshire'},
{ town: 'Mitcham', council: 'Surrey'},
{ town: 'Mitcheldean', council: 'Gloucestershire'},
{ town: 'Mold', council: 'Clwyd'},
{ town: 'Monmouth', council: 'Gwent'},
{ town: 'Montgomery', council: 'Powys'},
{ town: 'Montrose', council: 'Angus'},
{ town: 'Morden', council: 'Surrey'},
{ town: 'Morecambe', council: 'Lancashire'},
{ town: 'Moretonhampstead', council: 'Devon'},
{ town: 'Morpeth', council: 'Northumberiand'},
{ town: 'Moscow', council: 'East Ayrshire'},
{ town: 'Motherwell', council: 'Lanarkshire'},
{ town: 'Musselburgh', council: 'Midlothian'},
{ town: 'Nailsea', council: 'Avon'},
{ town: 'Nairn', council: 'Inverness-shire'},
{ town: 'Nantwich', council: 'Cheshire'},
{ town: 'Narberth', council: 'Pembrokeshire'},
{ town: 'Neath', council: 'Neath Port Talbot'},
{ town: 'Nefyn', council: 'Gwynedd'},
{ town: 'Nelson', council: 'Lancashire'},
{ town: 'Nethy Bridge', council: 'Inverness-shire'},
{ town: 'New Malden', council: 'Surrey'},
{ town: 'New Mills', council: 'Derbyshire'},
{ town: 'Newark', council: 'Nottinghamshire'},
{ town: 'Newbury', council: 'Berkshire'},
{ town: 'Newcastle', council: 'Co Down'},
{ town: 'Newcastle', council: 'Staffordshire'},
{ town: 'Newcastle Emlyn', council: 'Dyfed'},
{ town: 'Newcastle upon Tyne', council: 'Tyne ＆ Wear'},
{ town: 'Newcastleton', council: 'Roxburghshire'},
{ town: 'Newent', council: 'Gloucestershire'},
{ town: 'Newhaven', council: 'East Sussex'},
{ town: 'Newmarket', council: 'Suffolk'},
{ town: 'Newport', council: 'Gwent'},
{ town: 'Newport', council: 'Isle of Wight'},
{ town: 'Newport', council: 'Shropshire'},
{ town: 'Newport Pagnell', council: 'Buckinghamshire'},
{ town: 'Newquay', council: 'Cornwall'},
{ town: 'Newton Abbot', council: 'Devon'},
{ town: 'Newtown', council: 'Powys'},
{ town: 'Newtown-le- Willows', council: 'Merseyside'},
{ town: 'Newtownabbey', council: 'Co Antrim'},
{ town: 'Newtownards', council: 'Co Down'},
{ town: 'North Berwick', council: 'East Lothian'},
{ town: 'North Shields', council: 'Tyne ＆ Wear'},
{ town: 'North Walsham', council: 'Norfolk'},
{ town: 'Northallerton', council: 'North Yorkshire'},
{ town: 'Northampton', council: 'Northamptonshire'},
{ town: 'Northwich', council: 'Cheshire'},
{ town: 'Northwood', council: 'Middlesex'},
{ town: 'Norwich', council: 'Norfolk'},
{ town: 'Nottingham', council: 'Nottinghamshire'},
{ town: 'Nottinghamshire', council: 'Nottinghamshire'},
{ town: 'Nuneaton', council: 'Warwickshire'},
{ town: 'Oakham', council: 'Leicestershire'},
{ town: 'Oban', council: 'Argyll'},
{ town: 'Okehampton', council: 'Devon'},
{ town: 'Oldham', council: 'Lancashire'},
{ town: 'Omagh', council: 'Co Tyrone'},
{ town: 'Ongar', council: 'Essex'},
{ town: 'Ormskirk', council: 'Lancashire'},
{ town: 'Orpington', council: 'Kent'},
{ town: 'Ossett', council: 'West Yorkshire'},
{ town: 'Oswestry', council: 'Shropshire'},
{ town: 'Otley', council: 'West Yorkshire'},
{ town: 'Oxford', council: 'Oxfordshire'},
{ town: 'Oxted', council: 'Surrey'},
{ town: 'Paignton', council: 'Devon'},
{ town: 'Paisley', council: 'Renfrewshire'},
{ town: 'Pakenham', council: 'Suffolk'},
{ town: 'Par', council: 'Cornwall'},
{ town: 'Pembroke', council: 'Dyfed'},
{ town: 'Penarth', council: 'South Glamorgan'},
{ town: 'Pencombe', council: 'Herefordshire'},
{ town: 'Penicuik', council: 'Midlothian'},
{ town: 'Penmaenmawr', council: 'Gwynedd'},
{ town: 'Penrhyndeudraeth', council: 'Gwynedd'},
{ town: 'Penrith', council: 'Cumbria'},
{ town: 'Penryn', council: 'Cornwall'},
{ town: 'Penzance', council: 'Cornwall'},
{ town: 'Pershore', council: 'Hereford ＆ Worcester'},
{ town: 'Perth', council: 'Perthshire'},
{ town: 'Peterborough', council: 'Cambridgeshire'},
{ town: 'Peterhead', council: 'Aberdeenshire'},
{ town: 'Petersfield', council: 'Hampshire'},
{ town: 'Petworth', council: 'West Sussex'},
{ town: 'Pevensey', council: 'East Sussex'},
{ town: 'Pewsey', council: 'Wiltshire'},
{ town: 'Pickering', council: 'North Yorkshire'},
{ town: 'Pinner', council: 'Middlesex'},
{ town: 'Pitlochry', council: 'Perthshire'},
{ town: 'Plymouth', council: 'Devon'},
{ town: 'Pocklington', council: 'East Riding of Yorkshire'},
{ town: 'Pontefract', council: 'West Yorkshire'},
{ town: 'Pontyclun', council: 'Mid Glamorgan'},
{ town: 'Pontypool', council: 'Torfaen'},
{ town: 'Pontypridd', council: 'Mid Glamorgan'},
{ town: 'Poole', council: 'Dorset'},
{ town: 'Pooley Bridge', council: 'Cumbria'},
{ town: 'Port Isaac', council: 'Cornwall'},
{ town: 'Port Talbot', council: 'West Glamorgan'},
{ town: 'Porthcawl', council: 'Mid Glamorgan'},
{ town: 'Porthmadog', council: 'Gwynedd'},
{ town: 'Portree', council: 'Isle of Skye'},
{ town: 'Portrush', council: 'Co Antrim'},
{ town: 'Portsmouth', council: 'Hampshire'},
{ town: 'Potters Bar', council: 'Hertfordshire'},
{ town: 'Poulton-le-Fylde', council: 'Lancashire'},
{ town: 'Prescot', council: 'Merseyside'},
{ town: 'Prestatyn', council: 'Clwyd'},
{ town: 'Preston', council: 'Lancashire'},
{ town: 'Prestwick', council: 'Ayrshire'},
{ town: 'Princes Risborough', council: 'Buckinghamshire'},
{ town: 'Prudhoe', council: 'Northumberland'},
{ town: 'Pulborough', council: 'West Sussex'},
{ town: 'Purley', council: 'Surrey'},
{ town: 'Pwllheli', council: 'Gwynedd'},
{ town: 'Radlett', council: 'Hertfordshire'},
{ town: 'Ramsey', council: 'Isle of Man'},
{ town: 'Ramsgate', council: 'Kent'},
{ town: 'Raughton Head', council: 'Cumbria'},
{ town: 'Rayleigh', council: 'Essex'},
{ town: 'Reading', council: 'Berkshire'},
{ town: 'Redcar', council: 'Cleveland'},
{ town: 'Redditch', council: 'Hereford and'},
{ town: 'Redhill', council: 'Surrey'},
{ town: 'Redruth', council: 'Cornwall'},
{ town: 'Reigate', council: 'Surrey'},
{ town: 'Retford', council: 'Nottmghamshire'},
{ town: 'Rhyl', council: 'Clwyd'},
{ town: 'Richmond', council: 'North Yorkshire'},
{ town: 'Richmond', council: 'Surrey'},
{ town: 'Rickmansworth', council: 'Hertfordshire'},
{ town: 'Riding Mill', council: 'Northumberland'},
{ town: 'Ringwood', council: 'Hampshire'},
{ town: 'Ripley', council: 'Derbyshire'},
{ town: 'Ripon', council: 'North Yorkshire'},
{ town: 'Robertsbridge', council: 'East Sussex'},
{ town: 'Rochdale', council: 'Lancashire'},
{ town: 'Rochester', council: 'Kent'},
{ town: 'Rochford', council: 'Essex'},
{ town: 'Rockbourne', council: 'Hampshire'},
{ town: 'Romford', council: 'Essex'},
{ town: 'Romsey', council: 'Hampshire'},
{ town: 'Ross-on-Wye', council: 'Herefordshire'},
{ town: 'Rossendale', council: 'Lancashire'},
{ town: 'Rothbury', council: 'Northumberland'},
{ town: 'Rotherham', council: 'South Yorkshire'},
{ town: 'Rothesay', council: 'Isle ofBute'},
{ town: 'Royston', council: 'Hertfordshire'},
{ town: 'Rugby', council: 'Warwickshire'},
{ town: 'Rugeley', council: 'Staffordshire'},
{ town: 'Ruislip', council: 'Middlesex'},
{ town: 'Runcorn', council: 'Cheshire'},
{ town: 'Rushden', council: 'Northamptonshire'},
{ town: 'Ruthin', council: 'Clwyd'},
{ town: 'Rye', council: 'East Sussex'},
{ town: 'Ryton', council: 'Tyne ＆ Wear'},
{ town: 'Saffron Walden', council: 'Essex'},
{ town: 'Salford', council: 'Lancashire'},
{ town: 'Salisbury', council: 'Wiltshire'},
{ town: 'Saltash', council: 'Cornwall'},
{ town: 'Saltburn-by-the-Sea', council: 'Cleveland'},
{ town: 'Saltcoats', council: 'Ayrshire'},
{ town: 'Sandbach', council: 'Cheshire'},
{ town: 'Sandhurst', council: 'Berkshire'},
{ town: 'Sandown', council: 'Isle of Wight'},
{ town: 'Sandwich', council: 'Kent'},
{ town: 'Sandy', council: 'Bedfordshire'},
{ town: 'Sanquhar', council: 'Dumfriesshire'},
{ town: 'Sawbridgeworth', council: 'Hertfordshire'},
{ town: 'Saxmundham', council: 'Suffolk'},
{ town: 'Scarborough', council: 'North Yorkshire'},
{ town: 'Scarinish', council: 'Isle of Tiree'},
{ town: 'Scunthorpe', council: 'South Humberside'},
{ town: 'Seaford', council: 'East Sussex'},
{ town: 'Seaham', council: 'Co Durham'},
{ town: 'Seahouses', council: 'Northumberland'},
{ town: 'Seaton', council: 'Devon'},
{ town: 'Sedbergh', council: 'Cumbria'},
{ town: 'Sedgefield', council: 'Co Durham'},
{ town: 'Selby', council: 'North Yorkshire'},
{ town: 'Selkirk', council: 'Selkirkshire'},
{ town: 'Settle', council: 'North Yorkshire'},
{ town: 'Sevenoaks', council: 'Kent'},
{ town: 'Shaftesbury', council: 'Wiltshire'},
{ town: 'Shap', council: 'Cumbria'},
{ town: 'Shawbost', council: 'Isle of Lewis'},
{ town: 'Sheffield', council: 'South Yorkshire'},
{ town: 'Shepperton', council: 'Middlesex'},
{ town: 'Shepton Mallet', council: 'Somerset'},
{ town: 'Sherborne', council: 'Dorset'},
{ town: 'Sheringham', council: 'Norfolk'},
{ town: 'Shetland', council: 'Isle of Shetland'},
{ town: 'Shifnal', council: 'Shropshire'},
{ town: 'Shipley', council: 'West Yorkshire'},
{ town: 'Shrewsbury', council: 'Shropshire'},
{ town: 'Sidcup', council: 'Kent'},
{ town: 'Sidmouth', council: 'Devon'},
{ town: 'Sittingbourne', council: 'Kent'},
{ town: 'Skegness', council: 'Lincolnshire'},
{ town: 'Skelmersdale', council: 'Lancashire'},
{ town: 'Skipton', council: 'North Yorkshire'},
{ town: 'Sleaford', council: 'Lincolnshire'},
{ town: 'Slough', council: 'Berkshire'},
{ town: 'Solihull', council: 'West Midlands'},
{ town: 'South Croydon', council: 'Surrey'},
{ town: 'South Queensferry', council: 'West Lothian'},
{ town: 'South Molton', council: 'Devon'},
{ town: 'South Petherton', council: 'Somerset'},
{ town: 'South Wirral', council: 'Merseyside'},
{ town: 'Southall', council: 'Middlesex'},
{ town: 'Southam', council: 'Warwickshire'},
{ town: 'Southampton', council: 'Hampshire'},
{ town: 'Southend-on-Sea', council: 'Essex'},
{ town: 'Southminster', council: 'Essex'},
{ town: 'Southport', council: 'Merseyside'},
{ town: 'Southsea', council: 'Hampshire'},
{ town: 'Southwell', council: 'Nottinghamshire'},
{ town: 'Sowerby', council: 'North Yorkshire'},
{ town: 'Spalding', council: 'Lincolnshire'},
{ town: 'Spilsby', council: 'Lincolnshire'},
{ town: 'St Albans', council: 'Hertfordshire'},
{ town: 'St Andrews', council: 'Fife'},
{ town: 'St Asaph', council: 'Clwyd'},
{ town: 'St Austell', council: 'Cornwall'},
{ town: 'St Clears', council: 'Carmarthenshire'},
{ town: 'St Helens', council: 'Merseyside'},
{ town: 'St Ives', council: 'Cornwall'},
{ town: 'St Leonards-on-Sea', council: 'East Sussex'},
{ town: 'Stafford', council: 'Staffordshire'},
{ town: 'Staines', council: 'Middlesex'},
{ town: 'Stamford', council: 'Lincolnshire'},
{ town: 'Stanford-le-Hope', council: 'Essex'},
{ town: 'Stanmore', council: 'Middlesex'},
{ town: 'Stevenage', council: 'Hertfordshire'},
{ town: 'Stirling', council: 'Stirlingshire'},
{ town: 'Stockport', council: 'Cheshire'},
{ town: 'Stocksfield', council: 'Northumberland'},
{ town: 'Stockton-on-Tees', council: 'Cleveland'},
{ town: 'Stoke-on-Trent', council: 'Staffordshire'},
{ town: 'Stone', council: 'Staffordshire'},
{ town: 'Stonehaven', council: 'Kincardineshire'},
{ town: 'Stornoway', council: 'Isle of Lewis'},
{ town: 'Stourbridge', council: 'West Midlands'},
{ town: 'Stourport-on-Severn', council: 'Hereford ＆ Worcester'},
{ town: 'Stow-on-the-Wold', council: 'Gloucestershire'},
{ town: 'Stowmarket', council: 'Suffolk'},
{ town: 'Stranraer', council: 'Wigtownshire'},
{ town: 'Stratford-upon-Avon', council: 'Warwickshire'},
{ town: 'Strathcarron', council: 'Ross-shire'},
{ town: 'Strathaven', council: 'South Lanarkshire'},
{ town: 'Strathpeffer', council: 'Ross-shire'},
{ town: 'Street', council: 'Somerset'},
{ town: 'Stroud', council: 'Gloucestershire'},
{ town: 'Sudbury', council: 'Suffolk'},
{ town: 'Sunbury-on-Thames', council: 'Middlesex'},
{ town: 'Sunderland', council: 'Tyne ＆ Wear'},
{ town: 'Surbiton', council: 'Surrey'},
{ town: 'Sutton', council: 'Surrey'},
{ town: 'Sutton Coldfield', council: 'West Midlands'},
{ town: 'Sutton-in-Ashfield', council: 'Nottinghamshire'},
{ town: 'Swaffham', council: 'Norfolk'},
{ town: 'Swanage', council: 'Dorset'},
{ town: 'Swanley', council: 'Kent'},
{ town: 'Swansea', council: 'West Glamorgan'},
{ town: 'Swindon', council: 'Wiltshire'},
{ town: 'Tain', council: 'Ross-shire'},
{ town: 'Talybont', council: 'Gwynedd'},
{ town: 'Tamworth', council: 'Staffordshire'},
{ town: 'Tarbert', council: 'Argyll'},
{ town: 'Tarporley', council: 'Cheshire'},
{ town: 'Taunton', council: 'Somerset'},
{ town: 'Tavistock', council: 'Devon'},
{ town: 'Teddington', council: 'Middlesex'},
{ town: 'Teignmouth', council: 'Devon'},
{ town: 'Telford', council: 'Shropshire'},
{ town: 'Temple Cloud', council: 'Somerset'},
{ town: 'Templecombe', council: 'Somerset'},
{ town: 'Tenby', council: 'Dyfed'},
{ town: 'Tewkesbury', council: 'Gloucestershire'},
{ town: 'Thame', council: 'Oxfordshire'},
{ town: 'Thanet', council: 'Kent'},
{ town: 'Thatcham', council: 'Berkshire'},
{ town: 'Thetford', council: 'Norfolk'},
{ town: 'Thirsk', council: 'North Yorkshire'},
{ town: 'Thornton Heath', council: 'Surrey'},
{ town: 'Thurso', council: 'Caithness'},
{ town: 'Tilbury', council: 'Essex'},
{ town: 'Tipton', council: 'West Midlands'},
{ town: 'Tiverton', council: 'Devon'},
{ town: 'Todmorden', council: 'West Yorkshire'},
{ town: 'Tonbridge', council: 'Kent'},
{ town: 'Torquay', council: 'Devon'},
{ town: 'Torrington', council: 'Devon'},
{ town: 'Totland Bay', council: 'Isle of Wight'},
{ town: 'Towcester', council: 'Northamptonshire'},
{ town: 'Tranent', council: 'East Lothian'},
{ town: 'Tredegar', council: 'Gwent'},
{ town: 'Tring', council: 'Hertfordshire'},
{ town: 'Trowbridge', council: 'Wiltshire'},
{ town: 'Truro', council: 'Cornwall'},
{ town: 'Tunbridge Wells', council: 'Kent'},
{ town: 'Turriff', council: 'Aberdeenshire'},
{ town: 'Twickenham', council: 'Middlesex'},
{ town: 'Tywyn', council: 'Gwynedd'},
{ town: 'Uckfield', council: 'East Sussex'},
{ town: 'Ulverston', council: 'Cumbria'},
{ town: 'Umberleigh', council: 'Devon'},
{ town: 'Uttoxeter', council: 'Staffordshire'},
{ town: 'Uxbridge', council: 'Middlesex'},
{ town: 'Ventnor', council: 'Isle ofWight'},
{ town: 'Wadebridge', council: 'Cornwall'},
{ town: 'Wakefield', council: 'West Yorkshire'},
{ town: 'Wallasey', council: 'Merseyside'},
{ town: 'Wallingford', council: 'Oxfordshire'},
{ town: 'Wallington', council: 'Surrey'},
{ town: 'Walsall', council: 'West Midlands'},
{ town: 'Walsingham', council: 'Norfolk'},
{ town: 'Waltham Cross', council: 'Hertfordshire'},
{ town: 'Walton on the Naze', council: 'Essex'},
{ town: 'Walton-on-Thames', council: 'Surrey'},
{ town: 'Wantage', council: 'Oxfordshire'},
{ town: 'Warboys', council: 'Cambridgeshire'},
{ town: 'Ware', council: 'Hertfordshire'},
{ town: 'Wareham', council: 'Dorset'},
{ town: 'Warley', council: 'West Midlands'},
{ town: 'Warminster', council: 'Wiltshire'},
{ town: 'Warrington', council: 'Cheshire'},
{ town: 'Warwick', council: 'Warwickshire'},
{ town: 'Warwickshire', council: 'Warwickshire'},
{ town: 'Washington', council: 'Tyne ＆ Wear'},
{ town: 'Watchet', council: 'Somerset'},
{ town: 'Watford', council: 'Hertfordshire'},
{ town: 'Wedmore', council: 'Somerset'},
{ town: 'Welling', council: 'Kent'},
{ town: 'Wellingborough', council: 'Northamptonshire'},
{ town: 'Wells', council: 'Somerset'},
{ town: 'Wells-next-the-Sea', council: 'Norfolk'},
{ town: 'Welshpool', council: 'Powys'},
{ town: 'Welwyn', council: 'Hertfordshire'},
{ town: 'Welwyn Garden City', council: 'Hertfordshire'},
{ town: 'Wem', council: 'Shropshire'},
{ town: 'Wembley', council: 'Middlesex'},
{ town: 'West Bromwich', council: 'West Midlands'},
{ town: 'West Byfleet', council: 'Surrey'},
{ town: 'West Drayton', council: 'Middlesex'},
{ town: 'West Heslerton', council: 'North Yorkshire'},
{ town: 'West Kilbride', council: 'Ayrshire'},
{ town: 'West Linton', council: 'Peeblesshire'},
{ town: 'West Malling', council: 'Kent'},
{ town: 'West Wickham', council: 'Kent'},
{ town: 'Westbury', council: 'Wiltshire'},
{ town: 'Westcliff-on-Sea', council: 'Essex'},
{ town: 'Westerham', council: 'Kent'},
{ town: 'Weston-super-Mare', council: 'Avon'},
{ town: 'Wetherby', council: 'West Yorkshire'},
{ town: 'Weybridge', council: 'Surrey'},
{ town: 'Weymouth', council: 'Dorset'},
{ town: 'Whatton', council: 'Nottinghamshire'},
{ town: 'Whitby', council: 'North Yorkshire'},
{ town: 'Whitchurch', council: 'Hampshire'},
{ town: 'Whitchurch', council: 'Shropshire'},
{ town: 'Whitehaven', council: 'Cumbria'},
{ town: 'Whitland', council: 'Dyfed'},
{ town: 'Whitley Bay', council: 'Tyne ＆ Wear'},
{ town: 'Whitstable', council: 'Kent'},
{ town: 'Wick', council: 'Caithness'},
{ town: 'Wickford', council: 'Essex'},
{ town: 'Wigan', council: 'Lancashire'},
{ town: 'Wigton', council: 'Cumbria'},
{ town: 'Wilmslow', council: 'Cheshire'},
{ town: 'Wimborne', council: 'Dorset'},
{ town: 'Wincanton', council: 'Somerset'},
{ town: 'Winchester', council: 'Hampshire'},
{ town: 'Windermere', council: 'Cumbria'},
{ town: 'Windsor', council: 'Berkshire'},
{ town: 'Winscombe', council: 'Somerset'},
{ town: 'Wirral', council: 'Merseyside'},
{ town: 'Wisbech', council: 'Cambridgeshire'},
{ town: 'Wishaw', council: 'Lanarkshire'},
{ town: 'Witham', council: 'Buckinghamshire'},
{ town: 'Witham', council: 'Essex'},
{ town: 'Witney', council: 'Oxfordshire'},
{ town: 'Woking', council: 'Surrey'},
{ town: 'Wokingham', council: 'Berkshire'},
{ town: 'Wolverhampton', council: 'West Midlands'},
{ town: 'Woodford Green', council: 'Essex'},
{ town: 'Worcester', council: 'Hereford ＆ Worcester'},
{ town: 'Workington', council: 'Cumbria'},
{ town: 'Worksop', council: 'Nottinghamshire'},
{ town: 'Wormbridge', council: 'Herefordshire'},
{ town: 'Worthing', council: 'West Sussex'},
{ town: 'Wotton-under-Edge', council: 'Gloucestershire'},
{ town: 'Wrexham', council: 'Clwyd'},
{ town: 'Wymondham', council: 'Norfolk'},
{ town: 'Yateley', council: 'Surrey'},
{ town: 'Yelverton', council: 'Devon'},
{ town: 'Yeovil', council: 'Somerset'},
{ town: 'York', council: 'North Yorkshire'}]
